#
# Use this configuration file to control what RobotPy packages are installed
# on your RoboRIO
#

[tool.robotpy]

# Version of robotpy this project depends on
robotpy_version = "2025.3.1.1"

# Packages to install on the robot, all versions are locked down to prevent versioning issues
# robotpy packages are prefixed with 'robotpy-'
requires = [
    "numpy",
    "photonlibpy==2025.2.1",
    "robotpy-navx==2025.0",
    "robotpy-rev==2025.0.2",
    "phoenix6==25.1.0",
    "robotpy-pathplannerlib==2025.2.5",
cv
]
